[package]
name = "mn-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
grammers-client = { git = "https://github.com/Lonami/grammers" }
grammers-session= { git = "https://github.com/Lonami/grammers" }
grammers-mtsender= { git = "https://github.com/Lonami/grammers" }
tokio = { version = "1.36.0", features = ["full"] }
dotenv = { version = "0.15.0"}
deepl = {version="0.4.5"}

chrono = { version = "0.4.33", features = ["serde"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
serde_with = "3.6.1"

tokio-stream = { version = "0.1.14", features = ["sync"] }
sqlx = { version = "0.7.3", features = ["postgres", "runtime-tokio", "tls-rustls", "macros", "migrate", "time"] }
tracing = "0.1.40"